name: Nextflow language server CI
# read more here: https://help.github.com/en/articles/workflow-syntax-for-github-actions#on

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compile
        run: |
          git clone --depth 1 https://github.com/nextflow-io/nextflow ../nextflow
          make

      - name: Test
        run: |
          make test
